version: '3.7'

services:
  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - .:/app
      - ./docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - app
      - db

  app:
    image: winspiker/whatmedo:latest
    restart: unless-stopped
    build:
      dockerfile: docker/Dockerfile
      context: .
    volumes:
      - .:/app

  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main
    ports:
      - "5432:5432"
    volumes:
      - conf-postgres:/docker-entrypoint-initdb.d/

volumes:
   conf-postgres:
      driver: local
      driver_opts:
        type: none
        device: $PWD/docker/conf/postgres
        o: bind


#  conf-nginx:
#    driver: local
#    driver_opts:
#      type: none
#      device: $PWD/docker/conf/nginx
#      o: bind
#  conf-php:
#    driver: local
#    driver_opts:
#      type: none
#      device: $PWD/docker/conf/php
#      o: bind
