version: '3.7'

services:
  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - .:/app
      - ./docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - app
      - database

  app:
    image: winspiker/whatmedo:latest
    restart: unless-stopped
    build:
      dockerfile: docker/Dockerfile
      context: .
    env_file:
      - .env.docker
    volumes:
      - .env:/app/.env.local
      - .:/app

  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    restart: unless-stopped
    logging:
      driver: none
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-main}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-main}
      POSTGRES_USER: ${POSTGRES_USER:-main}
    ports:
      - "5432:5432"
    volumes:
      - conf-postgres:/docker-entrypoint-initdb.d/

volumes:
   conf-postgres:
      driver: local
      driver_opts:
        type: none
        device: $PWD/docker/conf/postgres
        o: bind
