version: '3.7'

networks:
  web:
    external: true
    driver:  bridge


services:
  nginx:
    image: nginx
    restart: unless-stopped
    networks:
      - web
    volumes:
      - .:/app
      - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - chrome
      - app
      - database
  chrome:
    image: selenium/standalone-chrome:latest
    restart: unless-stopped
    hostname: chrome
    networks:
      - web
    privileged: true
    shm_size: 2g

  app:
    restart: unless-stopped
    build:
      dockerfile: docker/php/Dockerfile.dev
      context: .
    extra_hosts:
      - "host.internal.docker:host-gateway"
    depends_on:
      - chrome
    networks:
      - web
    env_file:
      - .env.docker
    volumes:
      - .env.dist:/app/.env
      - .:/app

  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    restart: unless-stopped
    logging:
      driver: none
    networks:
      - web
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-main}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-main}
      POSTGRES_USER: ${POSTGRES_USER:-main}
    ports:
      - "5432:5432"
    volumes:
      - conf-postgres:/docker-entrypoint-initdb.d/

volumes:
   conf-postgres:
      driver: local
      driver_opts:
        type: none
        device: $PWD/docker/postgres/conf
        o: bind
