App\Entity\Task:
  properties:
    title:
      - Length:
          min: 5
          max: 50
          minMessage: 'Title must be at least {{ limit }} characters long'
          maxMessage: 'Title cannot be longer than {{ limit }} characters'