controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

main:
    path: /
    controller: App\Controller\MainController::home
    methods: ['GET']
edit:
    path: task/{id}/edit
    controller: App\Controller\TaskController::edit
    methods: ['GET']

update:
    path: task/{id}/update
    methods: ['POST']
    controller: App\Controller\TaskController::update

remove:
    path: task/remove/{id}
    controller: App\Controller\TaskController::deleteTask

done:
    path: task/{id}/done
    controller: App\Controller\TaskController::doneTask

create:
    path: tasks/create
    methods: ['POST']
    controller: App\Controller\TaskController::createTask

create_fake:
    path: tasks/create/fake/{number}
    controller: App\Controller\TaskController::fakeCreateTask
    methods: ['GET']

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout