controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

todo_list:
    path: /
    controller: App\Controller\HomeController::home

login:
    path: /login
    controller: App\Controller\AuthController::login

edit:
    path: edit/{id}
    controller: App\Controller\HomeController::edit

updated:
    path: edit/{id}/updated
    methods: ['POST']
    controller: App\Controller\HomeController::updated

delete:
    path: delete/{id}
    controller: App\Controller\HomeController::deleteTask

done:
    path: done/{id}
    controller: App\Controller\HomeController::doneTask
create:
    path: create
    methods: ['POST']
    controller: App\Controller\HomeController::createTask