controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

main:
    path: /
    controller: App\Controller\MainController::home

edit:
    path: tasks/edit/{id}
    controller: App\Controller\TaskController::edit
    methods: ['GET']

update:
    path: task/{id}
    methods: ['PATCH']
    controller: App\Controller\TaskController::updated

delete:
    path: tasks/{id}
    controller: App\Controller\TaskController::deleteTask
    methods: ['DELETE']

done:
    path: tasks/{id}/done
    controller: App\Controller\TaskController::doneTask
    methods: ['PATCH']

create:
    path: tasks
    methods: ['POST']
    controller: App\Controller\TaskController::createTask

create_fake:
    path: tasks/fake
    controller: App\Controller\TaskController::fakeCreateTask
    methods: ['POST']

app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: ['GET']

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
    methods: ['POST']