controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

todo_list:
    path: /
    controller: App\Controller\HomeController::home

login:
    path: /login
    controller: App\Controller\AuthController::login

edit:
    path: edit/{id}
    controller: App\Controller\HomeController::edit

updated:
    path: edit/{id}/updated
    controller: App\Controller\HomeController::updated