controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

todo_list:
    path: /
    controller: App\Controller\HomeController::home

edit:
    path: edit/{id}
    controller: App\Controller\HomeController::edit

updated:
    path: edit/{id}/updated
    methods: ['POST']
    controller: App\Controller\HomeController::updated

delete:
    path: delete/{id}
    controller: App\Controller\HomeController::deleteTask

done:
    path: done/{id}
    controller: App\Controller\HomeController::doneTask
create:
    path: create
    methods: ['POST']
    controller: App\Controller\HomeController::createTask
create_fake:
    path: create_fake/{number}
    controller: App\Controller\HomeController::fakeCreateTask

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout